# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - node_modules

.scripts:
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  before_script:
    - apk update && apk upgrade && apk add python make g++
    - yarn install
  script:
    - yarn lint
    - yarn build
    - yarn test --coverage

node-lts:
  image: node:lts-alpine
  extends: .scripts

node-11:
  image: node:11-alpine
  extends: .scripts

node-12:
  image: node:12-alpine
  extends: .scripts
